### ISSUE TITLE
Error: JavaFX runtime components are missing, and are required to run this application

### ISSUE THREAD

**Issue by Adsana1221** [SACHSTech/ICS4U-JavaFXDemo#1]
when I run HelloWorld it says: JavaFX runtime components are missing, and are required to run this application

**Comment by mrfabroa** [comment]
This is the issue described in Step 8 of the  [install and setup instructions](https://docs.google.com/document/d/1s5oTmY8A8TDZu303p_DaH6CEAcC9xL8-aNX-pAxCcps/edit#bookmark=id.6cbq62ij8u2h).   The resolution was also emphasized in the corresponding video.  Here are the steps to resolve:  

1. go to the .vscode directory and open the `launch.json` file. Alternative command palette (ctrl+shift+p) and type in `open launch.json`
2. In the launch.json file, find the entry related to the class you are trying to run. For example, if the error occurred when trying to run the `HelloWorld.java` file, the entry would look like this:
```
{
      "type": "java",
      "name": "Launch HelloWorld",
      "request": "launch",
      "mainClass": "basic.HelloWorld",
      "projectName": "JavaFXDemo_a879dfd"
    }
```
To resolve this, copy this text:
```
"vmArgs": "--module-path /Users/<user>/<pathtojavafx>/javafx-sdk-11.0.2/lib --add-modules javafx.controls,javafx.fxml",
```
and edit it so that the file path to the `javafx-sdk-11.0.2` directory is correct.  Add your edited line to the launch.json entry, like this:
```
{
      "type": "java",
      "name": "Launch HelloWorld",
      "request": "launch",
      "vmArgs": "--module-path /Users/<user>/<pathtojavafx>/javafx-sdk-11.0.2/lib --add-modules javafx.controls,javafx.fxml",
      "mainClass": "basic.HelloWorld",
      "projectName": "JavaFXDemo_a879dfd"
    }
```
such that the line is pasted after the `"request": "launch",` line.   

3.  Save your the `launch.json` file and try running your java file again.
